@startuml
title PropDevelopment SmartHome Integration Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Собственник или жилец")
System(propdev, "Система PropDevelopment", "Услуги приобретения недвижимости и ее обслуживания")

System_Ext(uk, "Управляющие компании", "")
System_Ext(smarthome, "Сервисы Умный дом", "")
System_Ext(payment, "Платежные системы", "")

Rel(user, propdev, "Использует систему для управления сервисами Умного дома")
Rel(propdev, uk,"Получение счетов ЖКХ и сервисов Умного дома")
Rel(propdev, payment,"Оплата счетов ЖКХ и сервисов Умного дома")
Rel(propdev, smarthome,"Управление сервисами Умного дома")

@enduml