apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
    securityContext:
      privileged: true    
  restartPolicy: Never
