apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
    securityContext:
        runAsUser: 0
        runAsGroup: 0 
  restartPolicy: Never
